// DOM interaction tests use the compiled UI and actual Python HTTP handlers.
// No real browser, socket transport, or PDF renderer is emulated by this test.
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { readFile, mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createInterface } from 'node:readline';
const { JSDOM } = process.env.REDREVIEW_JSDOM ? await import(process.env.REDREVIEW_JSDOM) : await import('jsdom');
const uiURL = new URL(process.env.REDREVIEW_UI_ORIGIN || 'http://127.0.0.1:8844');
const temp = await mkdtemp(join(tmpdir(), 'redreview-ui-'));
const bridge = spawn('python3', ['-m','tests.transport',join(temp,'test.sqlite3'),uiURL.host],{stdio:['pipe','pipe','inherit'],env:{...process.env,REDREVIEW_TEST_DISCOVERY:'1'}});
const lines = createInterface({input:bridge.stdout});
const pending=[];
lines.on('line',line=>pending.shift()?.(JSON.parse(line)));
async function request(path, data, headers={}) {
 const reply = await new Promise(resolve=>{pending.push(resolve);bridge.stdin.write(JSON.stringify({path,data,headers:{Host:uiURL.host,...(data!==undefined?{Origin:uiURL.origin}:{}),...headers}})+'\n');});
 if(reply.error)throw new Error(reply.error);
 const body=Buffer.from(reply.body,'base64').toString('utf8');
 return {ok:reply.status>=200&&reply.status<300,status:reply.status,json:async()=>JSON.parse(body),text:async()=>body};
}
const dom = new JSDOM(await readFile('web/index.html','utf8'), {runScripts:'outside-only',url:uiURL.href});
const w=dom.window;
w.fetch=(path, options={})=>request(path,options.body?JSON.parse(options.body):undefined,options.headers);
w.confirm=()=>true;
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
w.HTMLDialogElement.prototype.close=function(){this.open=false;};
const document=w.document;
const $=id=>document.getElementById(id);
const wait = async check=>{for(let i=0;i<100;i++){if(check())return;await new Promise(r=>setTimeout(r,20));}throw new Error('UI timeout: '+document.body.textContent);};
const click=async id=>{assert.ok($(id),'Missing control '+id);$(id).click();await new Promise(r=>setTimeout(r,30));};
const setFile=(id,file)=>{Object.defineProperty($(id),'files',{value:[file],configurable:true});$(id).dispatchEvent(new w.Event('change'));};
const change=(id,value)=>{$(id).value=value;$(id).dispatchEvent(new w.Event('change',{bubbles:true}));};
try {
 w.eval((await readFile('web/app.js','utf8')).replace(/export\s*\{\s*\};?\s*$/, ''));
 await wait(()=>$('demo'));
 await click('demo');
 await wait(()=>document.querySelectorAll('[data-record]').length===4);
 assert.match(document.body.textContent,/All sample records and findings are synthetic/);
 assert.ok($('blinded').checked);
 await click('pdf-mode');
 assert.ok(document.querySelector('iframe[title*="SYNTHETIC"]'));
 await click('abstract-mode');
 await click('decision-exclude');
 await wait(()=>$('message').className==='error');
 assert.match($('message').textContent,/exclusion reason/);
 await click('decision-include');
 await wait(()=>document.querySelector('.history')?.textContent.includes('include'));
 const reviewerSelect=$('reviewer-select');
 change('reviewer-select',reviewerSelect.options[1].value);
 await wait(()=>document.querySelector('.history')===null);
 assert.ok(!document.body.textContent.includes('Reviewer 1 · include'));
 $('reason').value='Unrelated topic';
 $('notes').value='SECOND REVIEWER PRIVATE NOTE';
 await click('decision-exclude');
 await wait(()=>document.querySelector('.history')?.textContent.includes('Second') || document.querySelector('.history')?.textContent.includes('Reviewer 2 · exclude'));
 change('reviewer-select',$('reviewer-select').options[0].value);
 await wait(()=>document.querySelector('.history')?.textContent.includes('Reviewer 1 · include'));
 assert.ok(!document.body.textContent.includes('SECOND REVIEWER PRIVATE NOTE'));
 $('blinded').checked=false;
 $('blinded').dispatchEvent(new w.Event('change'));
 await wait(()=>document.body.textContent.includes('Reviewers disagree'));
 assert.match(document.body.textContent,/SECOND REVIEWER PRIVATE NOTE/);
 change('reviewer-select',$('reviewer-select').options[2].value);
 await wait(()=>$('adjudicate'));
 await click('adjudicate');
 await wait(()=>document.querySelector('.history')?.parentElement.textContent.includes('resolution'));
 await click('settings');
 change('stage','chart');
 await click('save-settings');
 await wait(()=>$('save-chart'));
 change('chart-status-2','value');
 $('chart-2').value='Exampleland';
 change('chart-status-6','na');
 await click('save-chart');
 await wait(()=>$('chart-2')?.value==='Exampleland');
 await click('import');
 const csvText=await readFile('fixtures/sample.csv','utf8');
 setFile('import-file',{name:'sample.csv',text:async()=>csvText});
 await wait(()=>$('map-title'));
 change('map-title','Article title');
 change('map-abstract','Summary');
 await click('do-import');
 assert.match($('modal-message').textContent,/Source database/);
 $('source').value='Synthetic CSV';
 await click('do-import');
 await wait(()=>document.querySelectorAll('[data-record]').length===5);
 await click('attach');
 const pdfBytes=await readFile('fixtures/synthetic-report.pdf');
 setFile('pdf-file',{name:'SYNTHETIC-test.pdf',size:pdfBytes.length,arrayBuffer:async()=>pdfBytes.buffer.slice(pdfBytes.byteOffset,pdfBytes.byteOffset+pdfBytes.byteLength)});
 await click('save-pdf');
 await wait(()=>document.querySelectorAll('iframe').length===2);
 await click('tab-duplicates');
 await wait(()=>$('merge-0'));
 await click('merge-0');
 await wait(()=>$('undo-0'));
 assert.equal($('merge-0'),null);
 await click('undo-0');
 await wait(()=>$('merge-0'));
 await click('tab-reports');
 assert.ok(document.querySelector('a[href*="category=audit"]'));
 assert.match(document.body.textContent,/Not modelled/);
 const projectId=$('project-select').value;
 const backup=await (await request('/api/backup?project='+projectId+'&blinded=false')).json();
 assert.equal(backup.entities.pdf.length,2);
 const csv=await (await request('/api/export?project='+projectId+'&category=charted&blinded=false')).text();
 assert.match(csv,/Exampleland/);
 $('blinded').checked=true;
 $('blinded').dispatchEvent(new w.Event('change'));
 await wait(()=>!document.querySelector('a[href*="category=audit"]'));
 assert.ok(!document.body.textContent.includes('SECOND REVIEWER PRIVATE NOTE'));
 await click('restore');
 setFile('backup-file',{name:'backup.json',size:JSON.stringify(backup).length,text:async()=>JSON.stringify(backup)});
 await click('do-restore');
 await wait(()=>$('project-select')?.options.length===3);
 assert.match($('project-select').selectedOptions[0].textContent,/restored/);
 await click('settings');
 await click('archive');
 await wait(()=>document.body.textContent.includes('Archived project'));
 await click('tab-screen');
 assert.ok($('save-chart').disabled);
 // Create a real review project and exercise discovery through backend snapshots.
 await click('new');
 $('project-name').value='Discovery review';
 await click('create-project');
 await wait(()=>$('project-select')?.selectedOptions[0].textContent==='Discovery review');
 await click('tab-discover');
 $('discovery-query').value='gardening';
 $('discovery-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 await wait(()=>document.querySelectorAll('[data-discovery]').length===2);
 assert.match(document.body.textContent,/Abstract not supplied/);
 assert.match(document.body.textContent,/Open-access status unknown/);
 await click('select-discovery');
 await click('import-discovery');
 await wait(()=>$('modal-body').textContent.includes('Imported 2;'));
 await click('close-modal');
 await click('select-discovery');
 await click('import-discovery');
 await wait(()=>$('modal-body').textContent.includes('exact duplicates 2'));
 await click('close-modal');
 await click('discovery-next');
 await wait(()=>document.body.textContent.includes('Next page article'));
 assert.match(document.body.textContent,/Page 2/);
 await click('discovery-prev');
 await wait(()=>document.body.textContent.includes('Cached retrieval'));
 $('discovery-query').value='empty-test';
 $('discovery-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 await wait(()=>document.body.textContent.includes('No articles found'));
 $('discovery-query').value='rate-limit-test';
 $('discovery-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 await wait(()=>document.body.textContent.includes('Retry in 60 seconds'));
 change('discovery-mode','doi');
 $('discovery-query').value='10.1000/test';
 $('discovery-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 await wait(()=>document.querySelectorAll('[data-discovery]').length===1);
 await click('tab-screen');
 await wait(()=>document.querySelectorAll('[data-record]').length===2);
 await click('decision-include');
 await wait(()=>document.querySelector('.history')?.textContent.includes('include'));
 console.log('PASS: discovery selection, project import, exact duplicate report, pagination, caching, empty results, rate limits, DOI lookup and imported-record screening.');
 console.log('PASS: DOM screening, error feedback, independent profiles, blinding, adjudication, charting, merge/undo, CSV mapping/import, PDF attachment, exports, backup restore and archiving.');
} catch (error) { console.error('UI TEST FAILURE:',error); await new Promise(r=>setTimeout(r,100)); throw error; } finally {
 dom.window.close();
 bridge.stdin.end();
 await new Promise(resolve=>bridge.on('exit',resolve));
 lines.close();
 await rm(temp,{recursive:true,force:true});
}
